### ISSUE TITLE
Add a benefits section please. 

### ISSUE THREAD

**Issue by bburns632** [UptakeOpenSource/cran-server#4]
It would go along way to add a benefits / why this is awesome section in the readme.  

Some questions might be: 
- what value does this provide?  
- why not just use public cran? 
- In which situation is this cran setup better than the regular public cran push-pull?

A flashy example would add value too.

**Comment by ntdef** [comment]
Thanks for opening an issue here! 😁 

So just to be clear, this isn't supposed to be better or worse than public CRAN. This app is supposed to fill a need for people who need to maintain a private package repository, due to IP constraints, etc.

Another question might be: why use this instead of a simple file system or FTP server (which is how CRAN used to be hosted and which base R supports)? The reason you would use this is if you were wanting to run a private CRAN repository in a Docker environment where (1) you don't have any guarantees about storage and (2) you may have multiple instances running and you want consistency and high availability. This app is for addressing those particular concerns.

I'll add a note in the README where I explain that.
